ARDUINO_DIR  = /home/renato/.local/share/umake/electronics/arduino/
ARDUINO_LIBS = Arduboy2 EEPROM SPI
BOARD_TAG    = leonardo
ARDUINO_PORT = /dev/ttyACM0

CPPFLAGS += -Werror
CFLAGS   += -Werror

include /usr/share/arduino/Arduino.mk

